### ISSUE TITLE
A generated .epub misunderstood by a Kobo eReader

### ISSUE THREAD

**Issue by rgarrigue** [lise-henry/epub-builder#10]
Hi there

I've this https://github.com/rgarrigue/songbook which build an epub through mdbook + mdbook-epub plugin, plugin which use this crate. The resulting epub (you can download it in my repo Releases) is seen a "Unauthorized to read due to Adobe DRM" (unaccurate French to English translation) by my Kobo H2O eReader.

I've reported it there https://github.com/Michael-F-Bryan/mdbook-epub/issues/28, and they adviced me to drop a word here too.

I don't know anything about epub & so on, but feel free to link me some epub to check on my eReader if you want to try possible issues.

**Comment by rgarrigue** [comment]
@lise-henry any idea on the topic ?

**Comment by crowdagger** [comment]
From what I see, the HTML files only contain the body part and is missing the beginning and end for a  full XHTML that is required to be understood as valid, e.g. 
```html
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<body>
...
</body>
</html>
```

**Comment by rgarrigue** [comment]
Ok. @Michael-F-Bryan, I guess this is mdBook epub plugin missing a little something maybe, mind checking ? My level in rust is ~ null.

**Comment by mvdnes** [comment]
It seems that, although not forbidden in the EPUB spec, some readers cannot open EPUB files whose zip central directory have a comment set. You might want to add `writer.set_comment("");` after [zip_library.rs line 43](https://github.com/lise-henry/epub-builder/blob/53ca88953305b9c011d5259e23e92919f6d280a6/src/zip_library.rs#L43). On my Kobo Aura 2 this seems to fix the problem, but please test it yourself first.

**Comment by crowdagger** [comment]
Oh, thank you!
