### ISSUE TITLE
Bump zip-rs dependency

### ISSUE THREAD

**Issue by JeremyAube** [lise-henry/epub-builder#11]
mvdnes/zip-rs#151

As discussed in the issue, zip-rs was adding a comment that caused epub files to have trouble. This issue is now fixed in the git repository but is still not live on cargo.io (https://crates.io/crates/zip).

When the new version is available on cargo.io (Probably going to be v0.5.7), we should upgrade to fix the issue in this repo.

**Comment by crowdagger** [comment]
Is that necessary despite this fix https://github.com/lise-henry/epub-builder/commit/7ab01be8a33f826a0bb857aa411f1de9f9e3d0ed ? It was meant to fix that (I tested it with the dummy example on my Kobo), but if it is necessary to bump the version, no problem https://github.com/lise-henry/epub-builder/commit/7ab01be8a33f826a0bb857aa411f1de9f9e3d0ed

**Comment by JeremyAube** [comment]
Oh I didn't see your fix, sorry! I don't believe this is necessary then as it was the only reason I was suggesting a version bumb.

Great Work 👍
