### ISSUE TITLE
Zip file uses wrong slashes on Windows

### ISSUE THREAD

**Issue by mdsherry** [lise-henry/epub-builder#4]
Zip files should always use forward-slashes in paths (see e.g. [this bug report](http://www.dsource.org/projects/tango/ticket/1666) for a citation).

In [three](https://github.com/lise-henry/epub-builder/blob/master/src/epub.rs#L241) [different](https://github.com/lise-henry/epub-builder/blob/master/src/epub.rs#L260) [places](https://github.com/lise-henry/epub-builder/blob/master/src/epub.rs#L309) in `epub.rs`, a path is created using `Path::new("OEBPS").join(...)`, which uses the default path item separator for the platform. On Windows, this is a backslash.

`ZipCommand` handles this correctly, but `ZipLibrary` passes the path on verbatim. The resulting EPUB fails validation at http://validator.idpf.org/ because of files mentioned in the manifest that it can't find (e.g. `OEBPS/foo.html`) and files that it can see but aren't in the manifest (e.g. `OEBPS\foo.html`).

A simple solution that I've tested locally is changing https://github.com/lise-henry/epub-builder/blob/master/src/zip_library.rs#L59 to 
```rust
let file = format!("{}", path.as_ref().display()).replace('\\', "/");
```
which feels like a hack, but works. I suspect a proper fix would involve also fixing up paths added to the manifest, in case a user adds an `EpubContent` with a `\` in it.

**Comment by crowdagger** [comment]
Sorry to have taken so much time, but it should be fixed (I used your suggestion, but only on Windows; I'll try to think of a better fix later). Thanks!
