### ISSUE TITLE
Cover image metadata

### ISSUE THREAD

**Issue by jajo-11** [lise-henry/epub-builder#6]
I noticed when generating eBooks with this library, that my eBook reader expect the metadata section for the cover image in `content.opf` to look like
 ```
<meta name="cover" content="cover-image" />
```
instead of the at the moment generated:

```
<meta name="cover" content="path/to/image.jpeg" />
```

(My eBook reader does not show a cover image with the current meta data, but the book is still usable)

this would be easy to fix in line 390 in epub.rs

Note: I don't have access to the epub spec so this 'issue' is based on my empirical observations and might not be an issue with actual epub spec compliance

**Comment by crowdagger** [comment]
Thanks for reporting that. If I understand correctly, I think "content" is, indeed, supposed to reference the id and not the path. I've just pushed a commit that fixes that; I'll just take a bit more time to test that it works correctly and doesn't introduce other issues before publishing a new version.
