### ISSUE TITLE
"This book can't be opened" for example book

### ISSUE THREAD

**Issue by paulkernfeld** [lise-henry/epub-builder#8]
I generated the example book by running:

```
cargo run --example test > test.epub && open test.epub
```

Trying to open the example book in MacOS Books, I see the following error:

<img width="962" alt="Screen Shot 2020-02-15 at 13 01 56" src="https://user-images.githubusercontent.com/433803/74592871-78c44f80-4ff3-11ea-88b9-6fcb26be292a.png">

I can tell from the splash screen and table of contents that the MacOS Books application is able to understand a lot of the structure of the book.

If the README example isn't intended to produce a 100% valid book, what do you think of adding a smaller example that is guaranteed to always produce a valid book as output? I would be happy to take a stab at this.

**Comment by paulkernfeld** [comment]
It looks like this error can be fixed by changing `dummy_content` to be simple valid XHTML. Is that a change you would endorse? As an EPUB noob, it took me a while to figure out what actually constitutes valid content for an EPUB XHTML document. I eventually found success with:

```
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<body>
<p>Text of the page</p>
</body>
</html>
```

I apologize if the content above has errors; I am finding it difficult to understand the interactions between the EPUB, XHTML, XML, and HTML standards.

**Comment by crowdagger** [comment]
Yes it would be nice, honestly it just that I was too lazy while writing the doc :) There is also the dummy content for the cover that will be a problem, I guess removing the cover for the example would be the simplest solution

**Comment by mabl** [comment]
Can you tag a release please? This solves my issues on a Kobo and it looks like many people run into this.

**Comment by crowdagger** [comment]
Done! (Should have done this months ago, sorry)

**Comment by Messiahhh** [comment]
Hello @lise-henry, is the `<?xml version="1.0" encoding="UTF-8"?>` definitely necessary for every page and xhtml?
And by the way, It seemed that the README.md still kepp the original `dummy_content` content.
